name = "Serendipity"
uuid = "27f29cf8-22c5-464c-927b-d3feee29a4ca"
authors = ["Mazen Alotaibi", "Jacob Zelko"]
version = "0.0.0"

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"

[compat]
julia = "1.5.0"
